### ISSUE TITLE
Move to composer/docker

### ISSUE THREAD

**Issue by RobLoach** [RobLoach/composer-docker#1]
Move the GitHub repository move to http://github.com/composer/docker or http://github.com/composer/dockerfile

**Comment by eugene-dounar** [comment]
@Seldaek expressed some scepticism about this idea https://twitter.com/seldaek/status/562208841707057152

**Comment by Seldaek** [comment]
I think we could have links in the docs, that solves the discoverability problem. Having it in the org itself has no benefit AFAIK?

**Comment by eugene-dounar** [comment]
Agreed. Discoverability is the main concern IMO

**Comment by RobLoach** [comment]
It's at https://registry.hub.docker.com/u/composer/composer/ . I've branded it with the Composer logo, and hopefully that gives enough discovery. If there's not anything else, would be good to close this issue. :+1: .

**Comment by pmoust** [comment]
:+1:
