### ISSUE TITLE
composer crashing on update install due to php hitting memory limit

### ISSUE THREAD

**Issue by tomwilderspin** [RobLoach/composer-docker#4]
Hey,

Noticed that running this container the composer process crashes out with only a couple of dependences (for example: Silex, phpUnit). This looks like it is linked to the same issue here: https://github.com/composer/composer/issues/2704

Have got a fix example here: https://registry.hub.docker.com/u/tomwilderspin/composer/dockerfile/
by increasing the max memory limit in the ini file. Pull request to follow with the amend :smile:

**Comment by RobLoach** [comment]
Fixed the INI location at https://github.com/RobLoach/composer-docker/issues/5 .... Let me know if it's good to go. Thanks so much for noticing this :+1: .

**Comment by tomwilderspin** [comment]
@RobLoach yeah the conf.d extend is nicer than my local modification happy to :+1: 

Thanks for the super quick fix!
