### ISSUE TITLE
reduce the size of the image

### ISSUE THREAD

**Issue by docteurklein** [RobLoach/composer-docker#8]
It currently is 1GB big, which is a little too much.

**Comment by eugene-dounar** [comment]
After https://github.com/RobLoach/composer-docker/pull/7 was merged it reduced a little. 
```
composer/composer            latest              8cc91353b1c3        16 hours ago        628.9 MB
composer/composer            1.0.0-alpha9        d216f27e391f        16 hours ago        482.8 MB
composer/composer            master              a201582740fe        16 hours ago        482.8 MB
```

For some reason ```latest``` points to alpha8, which was not affected by the PR#7 Hence it's larger

**Comment by docteurklein** [comment]
thanks :)

**Comment by eugene-dounar** [comment]
It won't be much smaller though. The base PHP image is ~380Mb. Composer image should have git, subversion and mercurial, they take some disk space.

**Comment by RobLoach** [comment]
Anything else we could do to reduce the size? I'm considering closing this.

**Comment by eugene-dounar** [comment]
Yeah, removing apt cache saves about 30Mb. Will send a PR later.
