### ISSUE TITLE
Could not parse version constraint ^1.0.2: Invalid version string "^1.0.2"

### ISSUE THREAD

**Issue by pmoust** [RobLoach/composer-docker#9]
I get;
```
[UnexpectedValueException]
  Could not parse version constraint ^1.0.2: Invalid version string "^1.0.2"
```

When running;
```
docker run -it --rm -v `pwd`:/app/ composer/composer:latest install
```

Could you re-trigger an automated build to get latest composer.phar into the image?

**Comment by RobLoach** [comment]
@pmoust Triggered an automated build for it. What's your Docker username? I'll add you as a maintainer.

**Comment by pmoust** [comment]
@RobLoach it's `pmoust`
